macos_instance:
  image: ghcr.io/cirruslabs/macos-monterey-base:latest

task:
  script: |
      set -x
      echo "Hello World from macOS!"
      uname -a
      python3 --version --version
      which -a tar
      tar --version
      which -a gtar
      gtar --version
