#!/usr/bin/env python3
import argparse
import json
import os
import urllib.request


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument('repo_id', type=int)
    parser.add_argument('username')
    args = parser.parse_args()

    req = urllib.request.Request(
        f'https://api.github.com/repositories/{args.repo_id}/collaborators/{args.username}/permission',
        headers={'Authorization': f'token {os.environ["GITHUB_TOKEN"]}'},
    )
    resp = urllib.request.urlopen(req, timeout=10)
    contents = json.load(resp)

    has_permission = json.dumps(contents['permission'] in {'admin', 'write'})
    print(f'::set-output name=has-permission::{has_permission}')

    return 0


if __name__ == '__main__':
    raise SystemExit(main())
