name: Retract Release
on:
  issue_comment:
    types: [created]
jobs:
  retract:
    runs-on: ubuntu-latest
    name: Retract a release
    # not a pull request and has `#contains` on a line by itself
    # fromJSON is used to process escape sequences
    if: |
      !github.event.issue.pull_request &&
      contains(
        fromJSON('"\r\n#retract\r\n"'),
        format(fromJSON('"\r\n{0}\r\n"'), github.event.comment.body)
      )
    steps:
    - run: echo hi
    - run: python -c 'import os; print(repr(os.environ["WAT"]))'
      env:
        WAT: ${{github.event.comment.body}}
