name: main
on:
  pull_request:
  push:
    branches: [main]

jobs:
  main:
    name: main
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: echo hi
    - run: uname -a
    - uses: asottile-sentry/test-action-repo@c6a5ce473bcb95d088ad5e7672dc875d8867282e
