on:
  pull_request_target:
    types: [labeled, opened, reopened, synchronize]
  
# disable special privileges
permissions:
  # needed for `actions/checkout` to clone the code
  contents: read
    
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: echo hi
    - run: jq . <<< "$EVENT"
      env:
        EVENT: ${{ toJSON(github.event) }}
