on:
  pull_request_target:
    types: [labeled, opened, reopened, synchronize]
  
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: echo hi
    - run: jq . <<< "$EVENT"
      env:
        EVENT: ${{ toJSON(github.event.pull_request) }}
