on:
  pull_request_target:
    types: [labeled, opened, reopened, synchronize]

# disable special privileges
permissions:
  # needed for `actions/checkout` to clone the code
  contents: read
  # needed to remove the label
  pull-requests: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: permissions
      run: |
        python3 -uS .github/workflows/prt/setup \
            --repo-id ${{ github.event.repository.id }} \
            --pr ${{ github.event.number }} \
            --username ${{ github.event.pull_request.user.login }} \
            --event ${{ github.event.action }} \
            --label-names ${{ toJSON(github.event.pull_request.labels.*.name) }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: jq . <<< "$EVENT"
      env:
        EVENT: ${{ toJSON(github.event) }}
    - name: sensitive step
      run: echo you pass go!
