name: debug expr
on:
  issue_comment:
    types: [created]
jobs:
  t:
    runs-on: ubuntu-latest
    name: t
    steps:
    - run: python -c 'import os; print(repr(os.environ["WAT1"])); print(repr(os.environ["WAT2"]))'
      env:
        WAT1: ${{ fromJSON('"\r\n#retract\r\n"') }}
        WAT2: ${{ format(fromJSON('"\r\n{0}\r\n"'), github.event.comment.body) }}
